name: Instagram Auto Post

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 11 * * *'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:

      - name: Get Product
        run: |
          curl https://instagram-auto-post.onrender.com/product > product.json

      - name: Extract Data
        run: |
          PRODUCT_NAME=$(cat product.json | jq -r '.product_name')
          IMAGE=$(cat product.json | jq -r '.image')
          CAPTION=$(cat product.json | jq -r '.caption')

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "CAPTION=$CAPTION" >> $GITHUB_ENV

      - name: Post Image
        run: |
          curl -X POST "https://graph.facebook.com/v18.0/${{ secrets.INSTAGRAM_ACCOUNT_ID }}/media" \
          -F "image_url=$IMAGE" \
          -F "caption=$CAPTION" \
          -F "access_token=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}"
